### ISSUE TITLE
Can't login anymore by Ziggo. Need an authentication code via a SMS

### ISSUE THREAD

**Issue by JanStalenburg** [Sholofly/arrisdcx960#39]
**Describe the bug**
Can't login anymore by Ziggo. Need an authentication code via a SMS

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version of the component**
1.2.0

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    arris_dcx960: debug
```

**Additional context**
